# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0006_partial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credentials', models.TextField(db_column=b'credentials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFacebookData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.TextField(db_column=b'likes')),
                ('photos', models.TextField(db_column=b'photos')),
                ('posts', models.TextField(db_column=b'posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.CreateModel(
            name='UserFacebookPhotoAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField(db_column=b'photo')),
                ('keywords', models.TextField(db_column=b'keywords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
    ]
