# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
        ('optimum', '0002_auto_20170526_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacebookPhotoAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.TextField(db_column=b'photo')),
                ('keywords', models.TextField(db_column=b'keywords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
    ]
