# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimum', '0003_userfacebookphotoanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfacebookdata',
            name='photos',
        ),
        migrations.AddField(
            model_name='userfacebookdata',
            name='tagged_photos',
            field=models.TextField(db_column=b'tagged_photos', default=b''),
        ),
        migrations.AddField(
            model_name='userfacebookdata',
            name='uploaded_photos',
            field=models.TextField(db_column=b'uploaded_photos', default=b''),
        ),
        migrations.AlterField(
            model_name='userfacebookdata',
            name='likes',
            field=models.TextField(db_column=b'likes', default=b''),
        ),
        migrations.AlterField(
            model_name='userfacebookdata',
            name='posts',
            field=models.TextField(db_column=b'posts', default=b''),
        ),
    ]
