# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
        ('optimum', '0004_auto_20170613_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacebookPostsAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.TextField(db_column=b'post', default=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
    ]
