# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimum', '0006_aggregatedfacebookdataanalysis_userfacebooklikesanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacebookdata',
            name='random_id',
            field=models.TextField(db_column=b'random_id', default=b''),
        ),
    ]
